# Site settings
title: Firas Cheaib
description: Portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:4000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Firas Cheaib
user_subtitle: Software Engineer and Aspiring Game Developer
user_description: Software Engineering Bachelor Student
email: firascheaib@gmail.com
github_username:  firsou
linkedin_username:  firascheaib

# Google-analytics
google-analytics:
  id: "UA-115360692-1"

sass:
  sass_dir: css
  style: compressed
